package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFindItinerary(t *testing.T) {
	testCases := []struct {
		name    string
		tickets [][]string
		want    []string
	}{
		{
			name: "example 1",
			tickets: [][]string{
				{"MUC", "LHR"},
				{"JFK", "MUC"},
				{"SFO", "SJC"},
				{"LHR", "SFO"},
			},
			want: []string{
				"JFK", "MUC", "LHR", "SFO", "SJC",
			},
		},
		{
			name: "example 2",
			tickets: [][]string{
				{"JFK", "SFO"},
				{"JFK", "ATL"},
				{"SFO", "ATL"},
				{"ATL", "JFK"},
				{"ATL", "SFO"},
			},
			want: []string{
				"JFK", "ATL", "JFK", "SFO", "ATL", "SFO",
			},
		},
		{
			name: "test case 1",
			tickets: [][]string{
				{"AXA", "EZE"},
				{"EZE", "AUA"},
				{"ADL", "JFK"},
				{"ADL", "TIA"},
				{"AUA", "AXA"},
				{"EZE", "TIA"},
				{"EZE", "TIA"},
				{"AXA", "EZE"},
				{"EZE", "ADL"},
				{"ANU", "EZE"},
				{"TIA", "EZE"},
				{"JFK", "ADL"},
				{"AUA", "JFK"},
				{"JFK", "EZE"},
				{"EZE", "ANU"},
				{"ADL", "AUA"},
				{"ANU", "AXA"},
				{"AXA", "ADL"},
				{"AUA", "JFK"},
				{"EZE", "ADL"},
				{"ANU", "TIA"},
				{"AUA", "JFK"},
				{"TIA", "JFK"},
				{"EZE", "AUA"},
				{"AXA", "EZE"},
				{"AUA", "ANU"},
				{"ADL", "AXA"},
				{"EZE", "ADL"},
				{"AUA", "ANU"},
				{"AXA", "EZE"},
				{"TIA", "AUA"},
				{"AXA", "EZE"},
				{"AUA", "SYD"},
				{"ADL", "JFK"},
				{"EZE", "AUA"},
				{"ADL", "ANU"},
				{"AUA", "TIA"},
				{"ADL", "EZE"},
				{"TIA", "JFK"},
				{"AXA", "ANU"},
				{"JFK", "AXA"},
				{"JFK", "ADL"},
				{"ADL", "EZE"},
				{"AXA", "TIA"},
				{"JFK", "AUA"},
				{"ADL", "EZE"},
				{"JFK", "ADL"},
				{"ADL", "AXA"},
				{"TIA", "AUA"},
				{"AXA", "JFK"},
				{"ADL", "AUA"},
				{"TIA", "JFK"},
				{"JFK", "ADL"},
				{"JFK", "ADL"},
				{"ANU", "AXA"},
				{"TIA", "AXA"},
				{"EZE", "JFK"},
				{"EZE", "AXA"},
				{"ADL", "TIA"},
				{"JFK", "AUA"},
				{"TIA", "EZE"},
				{"EZE", "ADL"},
				{"JFK", "ANU"},
				{"TIA", "AUA"},
				{"EZE", "ADL"},
				{"ADL", "JFK"},
				{"ANU", "AXA"},
				{"AUA", "AXA"},
				{"ANU", "EZE"},
				{"ADL", "AXA"},
				{"ANU", "AXA"},
				{"TIA", "ADL"},
				{"JFK", "ADL"},
				{"JFK", "TIA"},
				{"AUA", "ADL"},
				{"AUA", "TIA"},
				{"TIA", "JFK"},
				{"EZE", "JFK"},
				{"AUA", "ADL"},
				{"ADL", "AUA"},
				{"EZE", "ANU"},
				{"ADL", "ANU"},
				{"AUA", "AXA"},
				{"AXA", "TIA"},
				{"AXA", "TIA"},
				{"ADL", "AXA"},
				{"EZE", "AXA"},
				{"AXA", "JFK"},
				{"JFK", "AUA"},
				{"ANU", "ADL"},
				{"AXA", "TIA"},
				{"ANU", "AUA"},
				{"JFK", "EZE"},
				{"AXA", "ADL"},
				{"TIA", "EZE"},
				{"JFK", "AXA"},
				{"AXA", "ADL"},
				{"EZE", "AUA"},
				{"AXA", "ANU"},
				{"ADL", "EZE"},
				{"AUA", "EZE"},
			},
			want: []string{},
		},
		{
			name: "test case 3",
			tickets: [][]string{
				{"JFK", "SFO"},
				{"JFK", "ATL"},
				{"SFO", "JFK"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
				{"ATL", "AAA"},
				{"AAA", "BBB"},
				{"BBB", "ATL"},
			},
			want: []string{},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, findItinerary(tc.tickets))
		})
	}
}
